name: Release Go

on:
  push:
    branches: [release/*]

jobs:
  publish-go:
    name: Create go/* tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cucumber/action-get-versions@v1.0.0
        id: versions
      - name: Create go/* tag
        run: |
          git tag "go/${{ steps.versions.outputs.changelog-latest-version }}"
          git push --tags
