# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test-ruby

on:
  push:
  pull_request:
    types:
      - merged
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby: [2.5, 2.6, 2.7, '3.0']
        include:
          - os: windows-latest
            node-version: '3.0'
          - os: macos-latest
            node-version: '3.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      working-directory: ./ruby
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: bundle exec rspec
      working-directory: ./ruby
      run: bundle exec rspec
